Fixed gem dependencies in Hoe configuration
Without this fix the following error would occur when doing a sudo gem install on a generated gem:

ERROR:  Error installing pkg/sake-1.1.0.gem:
        sake requires ParseTree >=2.1.1 (>= 0, runtime)

The gem dependency specification format in Hoe probably changed from an Array of strings to a Hash with gem => version pairs, causing this error.
This has been tested to work with hoe version 1.8.2